#!/usr/bin/env bash
# Run every measurement destined for the paper, once, against one known commit,
# and record what produced each number.
#
# WHY THIS EXISTS
# Results were previously gathered ad hoc, over weeks, against builds that kept
# changing underneath them - and nothing recorded which build. That is fine
# while iterating and useless afterwards: "which code produced Table 1?" had no
# answer, and at least one recorded table (the Phase 5 segment-duration study)
# was measured through a player that has since gained a combined MPD, an MSE
# buffer cap, a rewritten audio feed and a finer projection sphere. Those
# numbers describe software that no longer exists.
#
# The fix is not to re-measure more carefully. It is to make provenance a
# property of the measurement rather than something reconstructed later:
#
#   git tag paper-v1 && ./scripts/measure-for-paper.sh
#
# then cite the tag in the paper. Anyone - including a reviewer - can check out
# that tag, re-run this, and compare. That is the reproducibility claim the
# paper wants to make anyway, so it is not extra work; it is the work, done once,
# in a form that doubles as evidence.
#
# WHAT IT RECORDS
# Every run writes a manifest with the commit, the submodule commit, whether the
# tree was dirty, the tag, the host, the encoder versions, AND the EFFECTIVE
# docker compose configuration. That last one matters: the codec default was
# stated in four places and they disagreed, so a number measured "with the
# defaults" is meaningless unless the defaults are captured alongside it.
#
# Skipped measurements are recorded as SKIPPED with a reason. A run that
# silently omits something is worse than one that fails, because the gap is
# invisible in the results.
#
# Usage: scripts/measure-for-paper.sh [out-dir]
#   default out-dir: docs/measurements/<commit-or-tag>
set -uo pipefail
cd "$(dirname "$0")/.."

TAG=$(git describe --tags --exact-match 2>/dev/null || true)
SHA=$(git rev-parse --short HEAD)
DIRTY=""; [ -n "$(git status --porcelain)" ] && DIRTY=" (DIRTY TREE)"
OUT="${1:-docs/measurements/${TAG:-$SHA}}"
mkdir -p "$OUT"
MAN="$OUT/manifest.md"

say() { printf '[measure] %s\n' "$*"; }
run() {   # run <name> <description> <command...>
    local name="$1" desc="$2"; shift 2
    say "$name: $desc"
    local log="$OUT/$name.log" start rc
    start=$(date +%s)
    if "$@" > "$log" 2>&1; then rc=0; else rc=$?; fi
    printf '| `%s` | %s | %s | %ss | `%s.log` |\n' \
        "$name" "$desc" \
        "$([ $rc -eq 0 ] && echo PASS || echo "FAIL (rc=$rc)")" \
        "$(( $(date +%s) - start ))" "$name" >> "$MAN.rows"
    [ $rc -eq 0 ] || say "  ^ FAILED, see $log"
}
skip() {  # skip <name> <description> <reason>
    say "$1: SKIPPED - $3"
    printf '| `%s` | %s | **SKIPPED** | - | %s |\n' "$1" "$2" "$3" >> "$MAN.rows"
}

# ------------------------------------------------------------- provenance ---
say "recording provenance"
: > "$MAN.rows"
{
  echo "# Measurements for the paper"
  echo
  echo "Generated by \`scripts/measure-for-paper.sh\`. Every number in the paper"
  echo "that comes from this repository should be traceable to a run like this one."
  echo
  echo "## Provenance"
  echo
  echo "| field | value |"
  echo "|---|---|"
  echo "| commit | \`$SHA\`$DIRTY |"
  echo "| tag | ${TAG:-*(none - tag the commit before a citable run)*} |"
  echo "| hoast360 submodule | \`$(git -C hoast360 rev-parse --short HEAD 2>/dev/null || echo n/a)\` |"
  echo "| date (UTC) | $(date -u +%Y-%m-%dT%H:%M:%SZ) |"
  echo "| host | $(uname -s) $(uname -r) $(uname -m) |"
  echo "| cpu | $(sysctl -n machdep.cpu.brand_string 2>/dev/null || grep -m1 'model name' /proc/cpuinfo 2>/dev/null | cut -d: -f2- | xargs || echo unknown) |"
  echo "| ffmpeg | $(ffmpeg -version 2>/dev/null | head -1 | cut -d' ' -f1-3 || echo absent) |"
  echo "| SVT-AV1 | $(ffmpeg -hide_banner -f lavfi -i testsrc2=s=64x64:d=0.1 -c:v libsvtav1 -f null - 2>&1 | grep -oE 'SVT-AV1 Encoder Lib v[0-9.]+' | head -1 || echo n/a) |"
  echo "| docker | $(docker --version 2>/dev/null | cut -d, -f1 || echo absent) |"
  echo
  echo "### Effective configuration"
  echo
  echo 'Captured because "measured with the defaults" is not reproducible unless the'
  echo 'defaults are captured too - this repo had four disagreeing statements of the'
  echo 'video codec default at one point.'
  echo
  echo '```'
  docker compose config 2>/dev/null | grep -E "FFMPEG_FLAGS|DASH_NAME|SEG_|DASH_SPD" | sed 's/^ *//' || echo "(docker unavailable)"
  echo '```'
  echo
  echo "## Results"
  echo
  echo "| measurement | what it produces | outcome | wall | log |"
  echo "|---|---|---|---|---|"
} > "$MAN"

[ -n "$DIRTY" ] && say "WARNING: working tree is dirty - results are not citable"
[ -z "$TAG"   ] && say "WARNING: HEAD is untagged - tag it before a citable run"

# ------------------------------------------------------------ measurements --
if docker info >/dev/null 2>&1; then
    run pipeline "end-to-end stack gate: DASH appears, 16-ch Opus, codec per effective config" \
        ./scripts/test-pipeline.sh
else
    skip pipeline "end-to-end stack gate" "docker daemon not running"
fi

if [ -f content/vod/masters/directions_8k360_16ch.webm ] || [ -f content/demo.mp4 ]; then
    src=$([ -f content/demo.mp4 ] && echo content/demo.mp4 || echo content/vod/masters/directions_8k360_16ch.webm)
    run crf-sweep "delivery CRF sweep: bitrate and size per CRF" \
        ./scripts/crf-sweep.sh "$src" "$OUT/crf-sweep"
else
    skip crf-sweep "delivery CRF sweep" "no source: add content/demo.mp4 or a VOD master"
fi

if [ ! -d node_modules/playwright-core ] && [ ! -d node_modules/playwright ]; then
    skip lipsync "segment-duration study (Phase 5 table)" \
        "playwright absent - npm i -D playwright-core && npx playwright install chromium"
    skip smoke "player smoke test" "playwright absent (same as above)"
else
    # The lip-sync fixtures are gitignored build products, so a fresh clone
    # cannot reproduce the Phase 5 table until they are regenerated. That is a
    # reproducibility gap in its own right: build them first, do not let the
    # measurement fail with a bare 404.
    if compgen -G "lip-sync-test/dash_*" > /dev/null && [ -d lip-sync-test/dist ]; then
        run lipsync "segment-duration study: startup latency, playback ratio, stalls, A/V offset" \
            node scripts/measure-lipsync.js
    else
        skip lipsync "segment-duration study (Phase 5 table)" \
            "fixtures absent - run scripts/package-dash-variants.sh first (lip-sync-test/dash_*/ and dist/ are gitignored)"
    fi
    run smoke "player smoke: no console errors, clocks advance, HOA rotation follows drag" \
        node scripts/smoke-hoast360.js
fi

# ------------------------------------------------------------------ finish --
cat "$MAN.rows" >> "$MAN"; rm -f "$MAN.rows"
{
  echo
  echo "## Notes"
  echo
  echo "- A SKIPPED row is not a passing row. Anything skipped here is a number the"
  echo "  paper cannot cite from this run."
  echo "- Encode results are specific to the source, CRF and preset used. A figure"
  echo "  measured on one clip is not a general claim: a 10 s excerpt of one master"
  echo "  once suggested the opposite conclusion from the full 120 s encode."
} >> "$MAN"

say "done -> $MAN"
echo
sed -n '/^## Results/,$p' "$MAN"
