#!/bin/sh
# One-time bootstrap: prepare .env and, by default, the OWNER contribution route.
#
# WHY OWNER IS THE DEFAULT. If you are setting this box up, you are its owner,
# and the stream you want to push is your own. The owner route is built for
# exactly that: it authenticates you with a key, it never opens a keyless
# endpoint, and it binds to loopback here so nothing outside this machine can
# reach it. The guest endpoint answers a different question - "let SOMEBODY ELSE
# push to my box" - and because it takes no key at all it stays off until you
# deliberately turn it on. Setting up your own box should not require opening an
# endpoint for strangers, which is what pointing the OBS guides at the guest
# route used to imply.
#
# Safe to re-run: it never overwrites a file that already exists, so it cannot
# eat secrets you have already set.
#
# Windows: run this from Git Bash or WSL, or follow the manual steps it prints.
set -eu

cd "$(dirname "$0")/.."

ENV_FILE=".env"
OVR_FILE="docker-compose.override.yml"
OWNER_PORT=8891

say()  { printf '%s\n' "$*"; }
warn() { printf '%s\n' "$*" >&2; }

# A real random secret, or nothing. Never a fixed literal: a default secret in a
# public repository is not a secret, and the whole point of this script is that
# every install ends up with its own.
gen_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 24
    elif [ -r /dev/urandom ] && command -v od >/dev/null 2>&1; then
        od -An -tx1 -N24 /dev/urandom | tr -d ' \n'
    else
        return 1
    fi
}

# ---------------------------------------------------------------------------
# 1. .env
# ---------------------------------------------------------------------------
if [ -e "$ENV_FILE" ]; then
    say "keeping your existing $ENV_FILE (not overwritten)"
    # ...but complete the two things the owner route cannot run without, where
    # doing so is provably safe. An .env made by hand (say, a renamed
    # .env.example, which real first-time setups do) predates both secrets.
    #
    # RTMP_OWNER_KEY: replaced ONLY when missing, empty, or still one of the
    # two committed, publicly-known values - those are not secrets by
    # definition, so swapping them for a real one can break nothing but an
    # attacker's luck. A value you chose yourself is never touched.
    cur_key=$(grep -m1 '^RTMP_OWNER_KEY=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true)
    case "${cur_key:-}" in
        ''|CHANGE_ME_this_default_is_public|hoast_demo_owner)
            k=$(gen_secret || true)
            if [ -n "${k:-}" ]; then
                if grep -q '^RTMP_OWNER_KEY=' "$ENV_FILE"; then
                    awk -v k="$k" '/^RTMP_OWNER_KEY=/ {print "RTMP_OWNER_KEY=" k; next} {print}' \
                        "$ENV_FILE" > "$ENV_FILE.tmp" && mv "$ENV_FILE.tmp" "$ENV_FILE"
                else
                    printf '\nRTMP_OWNER_KEY=%s\n' "$k" >> "$ENV_FILE"
                fi
                say "RTMP_OWNER_KEY was missing or still the committed public default - replaced with a fresh secret"
            fi ;;
    esac
    # SRT_OWNER_PASSPHRASE: append when absent. The override below references
    # it, and the owner gateway refuses to start on an empty one, so without
    # this an existing .env means a crash-looping owner container.
    if ! grep -q '^SRT_OWNER_PASSPHRASE=' "$ENV_FILE"; then
        p=$(gen_secret || true)
        if [ -n "${p:-}" ]; then
            printf '\n# Added by scripts/setup.sh - the owner SRT route requires this.\nSRT_OWNER_PASSPHRASE=%s\n' \
                "$p" >> "$ENV_FILE"
            say "added the SRT_OWNER_PASSPHRASE the owner route requires"
        else
            warn "could not generate SRT_OWNER_PASSPHRASE (no openssl and no usable /dev/urandom);"
            warn "the owner route will not start until you set one in $ENV_FILE by hand"
        fi
    fi
else
    [ -e .env.example ] || { warn "no .env.example here - run this from the repo root"; exit 1; }
    cp .env.example "$ENV_FILE"

    owner_key=$(gen_secret || true)
    owner_pass=$(gen_secret || true)
    if [ -n "${owner_key:-}" ] && [ -n "${owner_pass:-}" ]; then
        # Replace the committed placeholder with a secret unique to this install,
        # and append the SRT passphrase the owner route requires. Written with a
        # temp file rather than `sed -i`, whose syntax differs between GNU and BSD.
        awk -v k="$owner_key" '/^RTMP_OWNER_KEY=/ {print "RTMP_OWNER_KEY=" k; next} {print}' \
            "$ENV_FILE" > "$ENV_FILE.tmp" && mv "$ENV_FILE.tmp" "$ENV_FILE"
        printf '\n# Generated by scripts/setup.sh - the owner SRT route requires this.\nSRT_OWNER_PASSPHRASE=%s\n' \
            "$owner_pass" >> "$ENV_FILE"
        say "created $ENV_FILE with a freshly generated owner key and passphrase"
    else
        warn "created $ENV_FILE, but could not generate secrets (no openssl and no usable /dev/urandom)."
        warn "Set RTMP_OWNER_KEY and SRT_OWNER_PASSPHRASE in it by hand before exposing this box."
    fi
fi

# ---------------------------------------------------------------------------
# 2. owner SRT route
# ---------------------------------------------------------------------------
if [ -e "$OVR_FILE" ]; then
    say "keeping your existing $OVR_FILE (not overwritten)"
    say "  if you want the owner route, copy the srt-gateway-owner block from"
    say "  docker-compose.override.yml.example into it."
else
    # Deliberately NOT a copy of docker-compose.override.yml.example: that file
    # also mounts ./custom/brand.json and binds a Tailscale address, neither of
    # which exists on a fresh clone, so copying it wholesale breaks the stack.
    # This writes only the owner service, bound to loopback.
    cat > "$OVR_FILE" <<'YAML'
# Written by scripts/setup.sh. Yours to edit; it is gitignored.
#
# The owner SRT route: push YOUR OWN 16-channel stream, authenticated, without
# opening the keyless guest endpoint. See docs/GUEST-ENDPOINT.md.
services:
  srt-gateway-owner:
    image: hoa360-srt-gateway:local
    build:
      context: ./services/srt-gateway
    environment:
      - SRT_ENABLED=1
      - SRT_MODE=owner
      - RTMP_OWNER_KEY=${RTMP_OWNER_KEY}
      - SRT_PASSPHRASE=${SRT_OWNER_PASSPHRASE}   # mandatory in owner mode
      - SRT_LATENCY_MS=${SRT_LATENCY_MS:-2000}
      - HOME=/tmp
      - XDG_CACHE_HOME=/tmp
      - GST_REGISTRY=/tmp/gst-registry.bin
    ports:
      # LOOPBACK: reachable from OBS on THIS machine and nowhere else, which
      # is the right default and wrong the moment you push from elsewhere.
      # To push from another device, put the address you will reach it on
      # here. A private VPN address (Tailscale/WireGuard) is the first choice.
      # 0.0.0.0 with the port forwarded is also supported - for streaming from
      # a venue back to a server a VPN cannot reach - and is safe here only
      # because the SRT passphrase is the connection's AES key, so libsrt
      # refuses the handshake before anything is parsed. See the "Pushing from
      # another machine" section of either OBS guide for what that costs.
      - "127.0.0.1:8891:8890/udp"
    read_only: true
    tmpfs:
      - /tmp
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges:true
    init: true
    depends_on:
      rtmp-ingest:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python3", "-c",
             "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8091/health', timeout=2)"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
YAML
    say "created $OVR_FILE with the owner SRT route on 127.0.0.1:$OWNER_PORT"
fi

# ---------------------------------------------------------------------------
# 3. what to do next
# ---------------------------------------------------------------------------
pass_now=$(grep -m1 '^SRT_OWNER_PASSPHRASE=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true)

say ""
say "Next:"
say "  docker compose up -d --build"
say ""
say "Then point OBS at (see docs/obs-windows.md or docs/obs-macos.md for the rest):"
if [ -n "${pass_now:-}" ]; then
    say "  srt://127.0.0.1:$OWNER_PORT?streamid=owner&passphrase=$pass_now&latency=2000000&pkt_size=1128"
else
    say "  srt://127.0.0.1:$OWNER_PORT?streamid=owner&passphrase=<SRT_OWNER_PASSPHRASE>&latency=2000000&pkt_size=1128"
fi
say ""
say "That passphrase is in $ENV_FILE, which is gitignored. It is not a secret from"
say "you, only from the network, so pasting it into your own OBS is the point."
say ""
say "Pushing from ANOTHER machine (a laptop, or OBS at a venue)? 127.0.0.1 above"
say "means this machine only. Change it in the ports line of $OVR_FILE: a private"
say "VPN address if you have one, or 0.0.0.0 with UDP $OWNER_PORT forwarded if you do"
say "not. Both are supported; that line's own comment explains what each costs."
say ""
say "Letting OTHER people push to this box is a separate, keyless route that is"
say "off by default: set GUEST_ENABLED=1 in $ENV_FILE. Read the trade-offs first"
say "in docs/GUEST-ENDPOINT.md - it takes no password from anyone."
